version: '3.6'
services:
  postgres:
    image: postgres:12
    restart: always
    volumes:
    - db_data:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: postgrespassword
      # HASURA_JWT_SECRET_KEY: ${ENCRYPTION_KEY}
  graphql-engine:
    image: hasura/graphql-engine:v2.8.1
    ports:
    - "8080:8080"
    extra_hosts: 
    - "localhost:host-gateway"
    depends_on:
    - "postgres"
    restart: always
    environment:
      ## postgres database to store Hasura metadata
      HASURA_GRAPHQL_METADATA_DATABASE_URL: postgres://postgres:postgrespassword@postgres:5432/postgres
      ## this env var can be used to add the above postgres database to Hasura as a data source. this can be removed/updated based on your needs
      PG_DATABASE_URL: postgres://postgres:postgrespassword@postgres:5432/postgres
      HASURA_GRAPHQL_ENABLE_CONSOLE: "true" # set to "false" to disable console
      HASURA_GRAPHQL_DEV_MODE: "true"
      HASURA_GRAPHQL_ENABLED_LOG_TYPES: startup, http-log, webhook-log, websocket-log, query-log
      HASURA_GRAPHQL_JWT_SECRET: '{"type": "HS256", "key": "GPeynnp35jBTYOJKhK5iiUjGz8Undv6X"}'      
      HASURA_GRAPHQL_ADMIN_SECRET: admin_secret

volumes:
  db_data:
